#!/usr/bin/env python3
"""Generate committed, grouped knowledge indexes from Markdown frontmatter."""

from __future__ import annotations

import argparse
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover - environment failure
    raise SystemExit(f"indexer dependency missing: {exc}; install PyYAML")


DOMAINS = ("conventions", "machines", "software", "ensembles")
DOMAIN_LABELS = {
    "conventions": "Conventions",
    "machines": "Machines",
    "software": "Software",
    "ensembles": "Ensembles",
}
SCOPE_LABELS = {
    "conventions": "convention",
    "machines": "machine",
    "software": "software project",
    "ensembles": "ensemble",
}
SCOPE_AXES = {
    "machine": "machines",
    "software": "software",
    "ensemble": "ensembles",
}


def read_frontmatter(path: Path) -> dict[str, Any] | None:
    text = path.read_text()
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError(f"{path}: unterminated YAML frontmatter")
    data = yaml.safe_load(text[4:end])
    if not isinstance(data, dict):
        raise ValueError(f"{path}: frontmatter must be a mapping")
    return data


def scoped_objects(metadata: dict[str, Any]) -> dict[str, set[str]]:
    objects: dict[str, set[str]] = defaultdict(set)
    scope = metadata.get("scope", [])
    if not isinstance(scope, list):
        return objects
    for item in scope:
        if item in ("all", "universal"):
            objects["conventions"].add("universal")
            continue
        if not isinstance(item, str) or ":" not in item:
            continue
        axis, name = item.split(":", 1)
        domain = SCOPE_AXES.get(axis)
        if domain and name:
            objects[domain].add(name.split("@", 1)[0])
    return objects


def collect_entries(root: Path) -> dict[str, dict[str, list[dict[str, str]]]]:
    entries: dict[str, dict[str, list[dict[str, str]]]] = {
        domain: defaultdict(list) for domain in DOMAINS
    }
    for storage_domain in DOMAINS:
        base = root / storage_domain
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.md")):
            if path.name == "INDEX.md":
                continue
            metadata = read_frontmatter(path)
            if metadata is None:
                continue
            required = ("title", "summary", "scope", "load_when")
            missing = [key for key in required if not metadata.get(key)]
            if missing:
                joined = ", ".join(missing)
                raise ValueError(f"{path}: missing index metadata: {joined}")

            objects = scoped_objects(metadata)
            if not objects:
                relative = path.relative_to(base)
                inferred = relative.parts[0] if len(relative.parts) > 1 else "general"
                objects[storage_domain].add(inferred)

            record = {
                "path": path.relative_to(root).as_posix(),
                "title": str(metadata["title"]),
                "summary": str(metadata["summary"]),
                "load_when": str(metadata["load_when"]),
            }
            for domain, names in objects.items():
                for name in names:
                    entries[domain][name].append(record)
    return entries


def escape_cell(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def render_index(
    root: Path, domain: str, groups: dict[str, list[dict[str, str]]]
) -> str:
    label = DOMAIN_LABELS[domain]
    lines = [
        "<!-- Generated by tools/build-index.py; do not edit. -->",
        f"# {label} Knowledge Index",
        "",
        f"Entries are grouped by scoped {SCOPE_LABELS[domain]}.",
        "",
    ]
    if not groups:
        lines.extend([f"_No published {domain} knowledge yet._", ""])
        return "\n".join(lines)

    index_dir = root / domain
    for group in sorted(groups):
        lines.extend(
            [
                f"## {group}",
                "",
                "| Knowledge | Summary | Load when |",
                "|---|---|---|",
            ]
        )
        records = sorted(
            groups[group], key=lambda item: (item["title"].casefold(), item["path"])
        )
        seen: set[str] = set()
        for record in records:
            if record["path"] in seen:
                continue
            seen.add(record["path"])
            target = os.path.relpath(root / record["path"], index_dir).replace(os.sep, "/")
            title = escape_cell(record["title"])
            summary = escape_cell(record["summary"])
            load_when = escape_cell(record["load_when"])
            lines.append(f"| [{title}]({target}) | {summary} | {load_when} |")
        lines.append("")
    return "\n".join(lines)


def expected_indexes(root: Path) -> dict[Path, str]:
    entries = collect_entries(root)
    return {
        root / domain / "INDEX.md": render_index(root, domain, entries[domain])
        for domain in DOMAINS
    }


def check_indexes(root: Path) -> int:
    stale: list[str] = []
    for path, expected in expected_indexes(root).items():
        try:
            actual = path.read_text()
        except FileNotFoundError:
            stale.append(f"missing generated index: {path.relative_to(root)}")
            continue
        if actual != expected:
            stale.append(f"stale generated index: {path.relative_to(root)}")
    for message in stale:
        print(message, file=sys.stderr)
    return 1 if stale else 0


def write_indexes(root: Path) -> int:
    for path, content in expected_indexes(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(path.relative_to(root))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        return check_indexes(root) if args.check else write_indexes(root)
    except (OSError, ValueError) as exc:
        print(f"index generation failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
