"""Read the runtime-data projection that operational tools use instead of YAML.

Operational tools run in every session, some inside hooks, and import only the standard
library (ARCHITECTURE.md §runtime-data). They read the JSON that
`tools/build-runtime-data.py` projects from the canonical YAML, through this module. It is
also the one home of the projection's layout: the generator imports it to decide where each
file goes, so writer and readers cannot disagree about a path.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

GENERATED = Path("tools") / "generated"
HANDBOOK = GENERATED / "handbook.json"
SCHEDULER_SURFACES = GENERATED / "scheduler-surfaces.json"
SURFACES_SOURCE = Path("conventions") / "scheduler-surfaces.yaml"
NOTE = "Generated by tools/build-runtime-data.py; edit the source YAML, never this file."


class RuntimeDataError(RuntimeError):
    """The projection is missing or unreadable; regenerating it is the remedy."""


def machine_path(name: str) -> Path:
    return GENERATED / "machines" / f"{name}.json"


def machine_source(name: str) -> Path:
    return Path("machines") / name / "machine.yaml"


def envelope(source: Path, data: Any) -> dict[str, Any]:
    """The on-disk form: the data, and where it came from for anyone who opens the file."""
    return {"note": NOTE, "source": source.as_posix(), "data": data}


def _load(root: Path, relative: Path) -> Any:
    path = Path(root) / relative
    try:
        text = path.read_text()
    except FileNotFoundError:
        raise RuntimeDataError(
            f"{relative.as_posix()} is missing; run tools/build-runtime-data.py"
        ) from None
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise RuntimeDataError(f"{relative.as_posix()}: invalid JSON: {exc}") from None
    if not isinstance(value, dict) or "data" not in value:
        raise RuntimeDataError(f"{relative.as_posix()}: not a runtime-data file")
    return value["data"]


def handbook(root: Path) -> dict[str, Any]:
    """The `handbook.yaml` blocks operational tools read; see its `runtime_data` block."""
    return _load(root, HANDBOOK)


def scheduler_surfaces(root: Path) -> dict[str, Any]:
    return _load(root, SCHEDULER_SURFACES)


def machine(root: Path, name: str) -> dict[str, Any] | None:
    """A machine profile, or None when the machine has no profile at all.

    A profile whose YAML exists but whose projection does not is a stale projection, not
    an unknown machine, and raises rather than reporting the machine as unprofiled.
    """
    if not (Path(root) / machine_source(name)).is_file():
        return None
    return _load(root, machine_path(name))
